### ISSUE TITLE
Automatically apply stuff like hiding/showing hair/jaw/arms.

### ISSUE THREAD

**Issue by Freywind** [geheur/weapon-animation-replacer#20]
When wearing a helm that obstructs the character's face (e.g. Neitiznot faceguard) and swapping to a helm that does not (e.g. Blue wizard hat), the character's head does not render at all (only the hat does).

Would it be possible to store the character's head/face so that this type of swap would work?

**Comment by geheur** [comment]
This is a known issue, you have to use show/hide on hair and jaw to fix this.
plugins like fashionscape fix this but I haven't got around to doing it yet in this one.

**Comment by geheur** [comment]
There isn't an easy way to tell if you should show or hide the player's hair/jaw because afaik the server automatically equips/unequips the player's hair/jaw so the client never knows the correct value without observing every helm/torso item being worn. This data can be collected, and it's something I wouldn't mind getting done at some point, along with data on weapons such as animations (and spells such as the trident, once spell transmog is in).

**Comment by Jin-Jiyunsun** [comment]
personally i wouldnt like it if hair was automatically hidden without an option to force it to show, i use the plugin to allow hair to still show when certain helm/hats are worn to prevent the "bald" look some head gear forces

**Comment by geheur** [comment]
coming in 3.3.1 <https://github.com/runelite/plugin-hub/pull/4322>

**Comment by geheur** [comment]
Released in 3.3.1.
