### ISSUE TITLE
Icon will not show up in plugin panel

### ISSUE THREAD

**Issue by Noobynoobnoob** [geheur/weapon-animation-replacer#28]
I installed the plug in but cannot access it from the plugin panel or the side bar :(

**Comment by geheur** [comment]
do you mean you can see the plugin in your plugin list, but you don't see the side panel icon (tiny dragon mace)?

I would restart the plugin and see if that fixes it.

Either way I'd also appreciate it if you could send me your `client.log` file, it's at `%userprofile%\.runelite\logs` on Windows or `$HOME/.runelite/logs` on Linux and macOS. You can send it to me on discord instead of here if you want, my user is `geheur#4508`

**Comment by Noobynoobnoob** [comment]
Yes i can see the plug in in my plug in list but there is no dragon mace on the side panel. I dont have a restart option other than pressed the orange bar to turn it on and off. That has not worked. Restarting runelite has not worked. I will message you on discord for more. Thanks for getting back to me, I appreciate it.

**Comment by Noobynoobnoob** [comment]
I sent an outgoing friends request just now. its Ohdamnitsazebra#0351
